import EducationSection from '@/components/EducationSection';
import HelloSection from '@/components/HelloSection';
import ProjectsSection from '@/components/ProjectsSection';
import SkillsSection from '@/components/SkillsSection';
import { IEducationItem, ISkill } from '@/global/types';
import { getEducacao, getHabilidades } from '@/utils/firebaseCollections';
import { GetStaticProps } from 'next';
import Head from 'next/head';

interface IProps {
  skills: ISkill[];
  education: IEducationItem[];
}

export default function Home({ skills, education }: IProps) {
  return (
    <>
      <Head>
        <title>Adriel Santos - Desenvolvedor Fullstack</title>

        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <HelloSection />
        <SkillsSection skills={skills} />
        <EducationSection education={education} />
        <ProjectsSection />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  try {
    const skills = await getHabilidades();
    const education = await getEducacao();
    return {
      props: { skills, education },
    };
  } catch (err) {}
  return {
    props: { education: [], skills: [] },
  };
};
