import HelloSection from '@/components/HelloSection';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Adriel Santos - Desenvolvedor Fullstack</title>

        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <HelloSection />
        {/* <SkillsSection />
        <EducationSection />
        <ProjectsSection /> */}
      </main>
    </>
  );
}
